[package]
name = "birru"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.8", features = ["cookies"]}
scraper = "0.12.0"
async-trait = "0.1.52"