[package]
name = "birru"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.4.3"
serde = "1.0.133"
scraper = "0.12.0"
async-trait = "0.1.52"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.8", features = ["cookies"] }
